version: "3.8"

services:
  app:
    container_name: ${APP_NAME}-app
    build:
      context: .
      dockerfile: ./docker/php/Dockerfile
    volumes:
      - ./src/:/var/www/html
      - vendor-volumes:/var/www/html/src/vendor
      - node_modules:/var/www/html/src/node_modules

  nginx:
    image: nginx
    container_name: ${APP_NAME}-nginx
    build:
      context: .
      dockerfile: ./docker/nginx/Dockerfile
    ports:
      - 8000:80
    volumes:
      - ./src/:/var/www/html
      - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
    - app

  db:
    image: mysql:8.4
    container_name: ${APP_NAME}-db
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_PASSWORD}
      TZ: 'Asia/Tokyo'
      MYSQL_DATABASE: ${APP_NAME}
      MYSQL_USER: ${APP_NAME}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
    command: mysqld --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci
    volumes:
      - mysql-volume:/var/lib/mysql
    ports:
      - 3306:3306

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: ${APP_NAME}-pma
    environment:
      PMA_HOST: db
      PMA_PORT: 3306
      UPLOAD_LIMIT: 500M
    ports:
      - "8080:80"
    depends_on:
      - db

# 上書き
volumes:
  mysql-volume:
  vendor-volumes:
  node_modules:
